name: 'camara_analytics'
version: '1.0.0'
config-version: 2
# Projeto de Analytics da Câmara dos Deputados (Medallion Architecture)

# Profile a ser usado
profile: 'camara_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração das Camadas Medallion
models:
  camara_analytics:
    bronze:
      +materialized: view
      +schema: bronze  # Gerará dev_bronze
    silver:
      +materialized: view
      +schema: silver  # Gerará dev_silver
    gold:
      +materialized: table
      +schema: gold    # Gerará dev_gold
